APP:
  PORT: 8080
  STATIC_FOLDER: "static"
  TOKEN_NAME: "Authorization"

  # TOKEN_EXPIRE: TOKEN失效时间（秒）
  TOKEN_EXPIRE: 86400
  AUTH_WHITE_LIST:
    - "/favicon.ico"
    - "/static"
    - "/sys/auth/login"
    - "/sys/auth/captcha"
    - "/sys/auth/captcha/enabled"

# 服务器环境仅供学习使用，请更换成自己本地的服务器
REDIS:
  HOST: "43.143.249.23"
  PORT: 6379
  DB: 1
  PASSWORD: "zKmv4k3p"

SQLALCHEMY:
  DATABASE_URI: "mysql+pymysql://demo:pdBGKGjRyX3Jb2Hn@43.143.249.23:3306/demo?charset=utf8"
  POOL_SIZE: 10
  POOL_TIMEOUT: 30
  POOL_RECYCLE: 3600
  TRACK_MODIFICATIONS: false
  COMMIT_ON_TEARDOWN: false
  SQLALCHEMY_ECHO: true