ENV: development
APP:
  STATIC_FOLDER: static
  TOKEN_NAME: Authorization
  TOKEN_EXPIRE: 86400
  AUTH_WHITE_LIST:
    - "/favicon.ico"
    - "/static/**"
    - "/sys/auth/**"
REDIS:
  HOST: localhost
  PORT: 6379
  DB: 0
SQLALCHEMY:
  DATABASE_URI: "mysql+pymysql://root:123456@localhost:3306/demo?charset=utf8"
  SQLALCHEMY_ECHO: False