ENV: production
APP:
  PORT: 8080
REDIS:
  HOST: flask-starter-redis
  PORT: 6379
  DB: 0
SQLALCHEMY:
  DATABASE_URI: "mysql+pymysql://root:pdBGKGjRyX3Jb2Hn@flask-starter-mysql:3306/demo?charset=utf8"
  SQLALCHEMY_ECHO: False